### ISSUE TITLE
Missing timestamp is treated as a non-fatal error

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly-evmconnect#53]
If the event listener fails to retrieve the timestamp for a block, it logs the problem and moves on.

https://github.com/hyperledger/firefly-evmconnect/blob/7a126b00a7c97127fe9a646f0c61d1e400b0041c/internal/ethereum/event_listener.go#L305

However, FireFly treats a missing timestamp as a fatal error and simply drops the event.

https://github.com/hyperledger/firefly/blob/3b728534d50c0cee6ed27890114b5a4c44fcec5c/internal/blockchain/ethereum/ethereum.go#L288

It seems like evmconnect should guarantee the presence of this field and retry as needed to get it. Alternately, if we want to downgrade the field to an optional one on FireFly, we'd need to communicate that in a release and adjust expectations for any apps built on top of FireFly.

**Comment by peterbroadhurst** [comment]
Completely agree @awrichar with the assessment - raised #57 to fix it
