### ISSUE TITLE
Return a better error when a transaction runs out of gas

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly-evmconnect#60]
If I submit a transaction with an insufficient `gas` value, and the EVM ends up running out of gas, it will simply stop executing and return a status of `0` in the transaction receipt. The transaction will still be included in a block, but will not be completed.

While the reason is not provided on the receipt in this case, it can be found by inspecting the transaction trace obtained by `debug.traceTransaction()`, if implemented: https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugtracetransaction

The failed step of the transaction will include an `error` field, such as the `error: "out of gas"` entry seen in this trace: [trace.txt](https://github.com/hyperledger/firefly-evmconnect/files/10969700/trace.txt)

It seems that some tools such as etherscan are able to extract this information for the user: https://etherscan.io/tx/0xda8c0b80d8e240a83c8f6b067c4656babeb13e8e0ece4fd4292aa06252f1285c

It would be convenient if evmconnect could also provide this functionality.

**Comment by hosie** [comment]
This would also help with other error conditions.  For example, if I have a `require` in my .sol such as
```solidity
require(balances[msg.sender] >= amount, "Not enough tokens");
```

and that causes the transaction to be reverted, then the error message is not returned on the receipt.  

Following @awrichar suggestion above, if I get the transaction hash from the receipt (e.g. using a local firefly stack)
```bash
TRANSACTION_HASH=$(curl -s "http://127.0.0.1:5000/api/v1/namespaces/default/operations/${OPERATION_ID}?fetchstatus=true" | jq -r .detail.transactionHash)
```

Then use that to read the transaction trace, convert the `returnValue` from hex to ascii (e.g. using `xxd`) and extract the strings
```bash
curl -s localhost:5100 -X POST --header 'Content-type: application/json' --data '{"jsonrpc":"2.0", "method":"debug_traceTransaction", "params":["'${TRANSACTION_HASH}'", {}], "id":1}' | jq  -r .result.returnValue | xxd -r -p | strings
```

then I do see the output
```
Not enough tokens
```

So this a) gives confidence in feasibility of the suggested fix and b) may serve as a short term workaround for anyone blocked by this in the meantime.

I have tried this on a local geth, provisioned by `ff init` and also on a hosted quorum node and it worked fine on both.

**Comment by hosie** [comment]
I have this on Besu and the same information is available on the transaction trace, however it is in a different place.  `result.returnValue` is empty string but the final operation in the `result.structLogs` arrays is a `REVERT` and its `reason` field contains the hex encoding for `Not enough tokens` (`114e6f7420656e6f75676820746f6b656e73`)....

```
{
        "pc": 829,
        "op": "REVERT",
        "gas": 76488,
        "gasCost": 0,
        "depth": 1,
        "stack": [
          "00000000000000000000000000000000000000000000000000000000a9059cbb",
          "0000000000000000000000000000000000000000000000000000000000000129",
          "000000000000000000000000b5855faa164db05e70fd3476e3540fc8c4053a01",
          "00000000000000000000000000000000000000000000000000000000000f4241",
          "0000000000000000000000000000000000000000000000000000000000000064",
          "0000000000000000000000000000000000000000000000000000000000000080"
        ],
        "memory": [
          "00000000000000000000000046ec33d9fd840ae95f36c3449cf46041ff6fb886",
          "0000000000000000000000000000000000000000000000000000000000000004",
          "0000000000000000000000000000000000000000000000000000000000000080",
          "0000000000000000000000000000000000000000000000000000000000000000",
          "08c379a000000000000000000000000000000000000000000000000000000000",
          "0000002000000000000000000000000000000000000000000000000000000000",
          "000000114e6f7420656e6f75676820746f6b656e730000000000000000000000",
          "0000000000000000000000000000000000000000000000000000000000000000"
        ],
        "storage": {},
        "reason": "0x8c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000114e6f7420656e6f75676820746f6b656e73000000000000000000000000000000"
      }
```

**Comment by hosie** [comment]
First attempts to code the `debug_traceTransaction` into evmconnect looking promising - https://github.com/hyperledger/firefly-evmconnect/compare/main...kaleido-io:firefly-evmconnect:error-receipt#diff-2a713d08838cbdad87e4601567a44175f4abeddfcdc8cf54a80824e900714e33R140

I have tested this with a quorum node and I see the following in the receipt now (NOTE the new field `returnValue` ...
```json
"receipt": {
      "blockHash": "0xb59d8ae5f0b42434e850d698a506e365d78c2d4eb4544f97e1b7183633dca519",
      "blockNumber": "137511",
      "contractLocation": null,
      "extraInfo": {
        "contractAddress": null,
        "cumulativeGasUsed": "23512",
        "from": "0x1368c2fbd50068004dac8d4f860080a3ab02b9f6",
        "gasUsed": "23512",
        "returnValue": "�y� Not enough tokens",
        "status": "0",
        "to": "0x8a50b857c856809b69b5622889a753d4d44e18fe"
      },
      "protocolId": "000000137511/000000",
      "success": false,
      "transactionIndex": "0"
    },

```


I'll try it out on Besu next.  And will try with out of gas conditions too.

I'm not sure whether to have this behaviour always on or make it configurable via conf files.

**Comment by peterbroadhurst** [comment]
`returnValue` here seems to be binary data rendered into a string field - we need to parse that as bytes in the right layer, using the `firefly-signer` utilities - like we do when `eth_call` fails prior to submission.

**Comment by hosie** [comment]
Yes.  It is an ABI encoded call to `Error(string)`.   Interesting thing about Besu is that it drops the leading `0` (using [toShortHexString](https://github.com/hyperledger/besu/blob/b084d80878ad3c94aa623bbc3635cdf1d406bc13/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/StructLog.java#LL59C54-L59C70))  so my naive `hex.DecodeString` doesn't work there.  I assume the `firefly-signer` utilities will know the right thing to do. So I'll try that. Thanks for the pointer.

**Comment by hosie** [comment]
Moved to using `firefly-signer` - https://github.com/hyperledger/firefly-evmconnect/commit/a4b06f28208720bd8268d5b618d0b9c645307d9d#

I couldn't find anything in `firefly-signer` that parses call data from hex string so I do that in a wrapper function here - https://github.com/hyperledger/firefly-evmconnect/commit/a4b06f28208720bd8268d5b618d0b9c645307d9d#diff-2a713d08838cbdad87e4601567a44175f4abeddfcdc8cf54a80824e900714e33R126-R143. Wondering if it is worth putting this wrapper into `firefly-signer`?
